version: 2.1

orbs:
  python: circleci/python@1.3.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: |
            cd image_preprocessing && tox
            cd ../neural_network && tox
          name: Test
  build-website:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            pip install notebook &&
            jupyter-nbconvert --to html demo.ipynb --stdout  > docs/index.html;
            git config user.email "m.tracewicz@gmail.com";
            git config user.name "Michał Tracewicz";
            x=`git diff --numstat | wc -l`
            [[ $x -eq 1 ]] &&
            git add docs/index.html &&
            git commit -m "Deployed website. [ci skip]" &&
            git push ||
            echo 'Nothing to do.'

workflows:
  main:
    jobs:
      - build-and-test
      - build-website
